version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: dzanto/yamdb
    restart: always
    volumes:
      - static_volume:/code/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    command: "gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:1.19.5-alpine
    volumes:
      - static_volume:/code/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:8000
    depends_on:
      - web